url: https://y7kim.github.io

# Site settings
title: Renee & Taylor
email: tpreynolds6@gmail.com
description: "Renee and Taylor's wedding website"

# Postal address (add as many lines as necessary)
address:
  - line: 1725 Mississauga Rd
  - line: Mississauga, ON L5H 2K4

people:
- name: Michael Reynolds
  pic: 1
  position: guy1 
- name: Cole Byvelds
  pic: 2
  position: guy2 
- name: Boris Baker
  pic: 3
  position: guy3


# Build settings
markdown: kramdown
permalink: pretty